### ISSUE TITLE
rpi3-mongodb3 container will crash when restart

### ISSUE THREAD

**Issue by speculatecat** [andresvidal/rpi3-mongodb3#1]
When I reboot the raspberry, and restart rpi-mongodb3 container,that can not start success. I check the log,and find the mian issues maybe mongo create a file in /data/db/mongo.lock. If remove this file,container can be started again. When use kill replace stop contianer, container can be started sucess too. But this problem seem not appear in libary/mongo for x86 plantform.How can I fix it?

**Comment by baumjr** [comment]
I solved this problem by enabling the journaling in MongoDB Startup.

e.g:
CMD ["mongod", "--journal"]

**Comment by LinusIvarsson** [comment]
> I solved this problem by enabling the journaling in MongoDB Startup.

> e.g:
> CMD ["mongod", "--journal"]

I have the same problem and added this but the problem still occur. Any other idea?

**Comment by mikevanis** [comment]
One year and a bit on, I also encountered this on Pi 3 and was able to solve it by overriding the default command and starting it with `CMD ["mongod", "--journal"]` as per @baumjr's suggestion.

**Comment by ghost** [comment]
how do I add this in docker-compose?
I'm getting Insufficient free space for journal files error
