### ISSUE TITLE
Can you update the database to version 4.0?

### ISSUE THREAD

**Issue by SeppPenner** [andresvidal/rpi3-mongodb3#2]
The latest version of MongoDB is 4.0. Can you update the Dockerfile, please?

**Comment by feluelle** [comment]
This won't work because version 4 only runs on 64Bit systems.

**Comment by feluelle** [comment]
See https://www.mongodb.com/download-center/community for more information on supported platforms and systems. **3.2.21** would work.

**Comment by SeppPenner** [comment]
@feluelle Mhm, okay. That doesn't really help me. Nevertheless, thenk you for the information.
